### ISSUE TITLE
too sus

### ISSUE THREAD

**Issue by fryingpanisafryingpan** [AakashSharma7269/linkOSs#3]
**Title**
too sus
**Steps to Reproduce**
observe sus
**Expected Result**
sus
**Actual Result**
sussssssssss

**Comment by AakashSharma7269** [comment]
This looks like a valid bug, might be fixed in a upcoming commit, ty

**Comment by AakashSharma7269** [comment]
A quick question
by sus here, you mean linkoss right?

**Comment by fryingpanisafryingpan** [comment]
yes fix pls too sus i want linkoss sus hunter badge

**Comment by AakashSharma7269** [comment]
Ok tysm, will be fixed in a future branch / commit

**Comment by LinkossLink** [comment]
[NAB] This is a feature request. You can suggest/upvote this at https://nowhere/feedback

**Comment by chweesee** [comment]
@LinkossLink forgot the .com

**Comment by LinkossLink** [comment]
You forgot it

**Comment by AakashSharma7269** [comment]
Claimed fixed, needs verification
moving to claimed fix , synced to linkoss boards
hopefully no longer sus™️

**Comment by AakashSharma7269** [comment]
Cannot reproduce
moving from claimed fixed to verified fix
