### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by chweesee** [AakashSharma7269/linkOSs#4]
documentation revamp

**Comment by AakashSharma7269** [comment]
Yes amogus documentation coming soon ™️

**Comment by LinkossLink** [comment]
[NAB] This is a feature request.

**Comment by AakashSharma7269** [comment]
No, this is an important bug which has been planned fixed

**Comment by chweesee** [comment]
i've added the label just in case

**Comment by chweesee** [comment]
@LinkossLink  are you happy now

**Comment by AakashSharma7269** [comment]
amogos bot triaged this as p0 priority

**Comment by AakashSharma7269** [comment]
Cannot reproduce, moving to verified fixed
