### ISSUE TITLE
Trying to run iso on debian using build.sh does not work

### ISSUE THREAD

**Issue by chweesee** [AakashSharma7269/linkOSs#5]
Open a debian based linux distro
Try to run the shell file
Observe how it shows errors

**Comment by AakashSharma7269** [comment]
Script uses mkarchiso as a dependency, not sure if Debian has it in its repositories

Will put out iso files in release section after adding kde gui ™️

**Comment by chweesee** [comment]
so looked around a bit and debian does not have this in its repositories, might check if rpm based distros like fedora or something has it so adding planned fixed for now, might just resort to arch then in case since it has pacman and pacman has mkarchiso

**Comment by AakashSharma7269** [comment]
Or I can just give you the iso when it's finished ™️

**Comment by AakashSharma7269** [comment]
@linkoss you better watch out

**Comment by LinkossLink** [comment]
> @linkoss you better watch out 

NO

**Comment by AakashSharma7269** [comment]
Wdymm this is a fantastic issue

**Comment by AakashSharma7269** [comment]
Fix will be pushed tomorrow morning.

**Comment by LinkossLink** [comment]
NAB Intended behavior

**Comment by AakashSharma7269** [comment]
This is indeed not a bug

**Comment by LinkossLink** [comment]
I can confirm that wasn't a bug as per myself

**Comment by chweesee** [comment]
youre a bug
